In [1]:
import pandas as pd

Serise 는 1차원 데이터 표현할 때 사용

In [7]:
s = pd.Series([1116, 12259, 65119, 16699], index=['서울','부산','인천','대구'])
s

서울     1116
부산    12259
인천    65119
대구    16699
dtype: int64

In [8]:
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [10]:
s.values

array([ 1116, 12259, 65119, 16699], dtype=int64)

In [11]:
s.name = '농작물 생산량(톤)'
s

서울     1116
부산    12259
인천    65119
대구    16699
Name: 농작물 생산량(톤), dtype: int64

In [13]:
# 각 value값에 적용
s1 = s/1000
s

서울     1116
부산    12259
인천    65119
대구    16699
Name: 농작물 생산량(톤), dtype: int64

In [23]:
s1.name = '농작물 생산량(k톤)'
s1.index.name = '지역구'
s1

지역구
서울     1.116
부산    12.259
인천    65.119
대구    16.699
Name: 농작물 생산량(k톤), dtype: float64

In [24]:
# 평균
(s/4456952*100).round(2) # round(2) : 소숫점 2째자리 까지 나타나도록

지역구
서울    0.03
부산    0.28
인천    1.46
대구    0.37
Name: 농작물 생산량(톤), dtype: float64

In [25]:
s

지역구
서울     1116
부산    12259
인천    65119
대구    16699
Name: 농작물 생산량(톤), dtype: int64

In [26]:
s[0], s['서울'] # 둘 다 접근 가능

(1116, 1116)

In [27]:
s[[1,0]] # 순서 지정 해서 가져오기 가능
s[['부산','서울']] # index로 가져오는 것 보다 key값으로 가져오는 것이 안전. index 값이 변경될 확률 높음.

지역구
부산    12259
서울     1116
Name: 농작물 생산량(톤), dtype: int64

In [30]:
# 10000톤 초과 20000톤 미만 생산한 지역 가져오기
# 산술 연산 뿐 아니라 and, or도 넣을 수 있다.
s[(s>10000) & (s<20000)]

지역구
부산    12259
대구    16699
Name: 농작물 생산량(톤), dtype: int64

In [31]:
# 비율 0.5%이상인 지역만 가져오기
s[(s/4456952*100) > 0.5]

지역구
인천    65119
Name: 농작물 생산량(톤), dtype: int64

In [33]:
s[1:3]

지역구
부산    12259
인천    65119
Name: 농작물 생산량(톤), dtype: int64

In [34]:
s['서울':'대구']

지역구
서울     1116
부산    12259
인천    65119
대구    16699
Name: 농작물 생산량(톤), dtype: int64

In [36]:
s.서울

1116

In [59]:
d1 = {'서울':1, '부산':2}
pd.Series(d1) #시리즈로 변환 가능, 순서가 고정되어서 고정되어있는 순서로 추가 가능.

서울    1
부산    2
dtype: int64

In [60]:
# 키,값쌍 출력 : itemm() 메소드 사용
for k,v in s.items():
    print(k,v)

서울 1116
부산 12259
인천 65119
대구 16699


In [61]:
print('서울' in s)
'서울' in s.keys()

True


True

In [62]:
s21 = pd.Series([1116, 12259, 65119, 16699], index=['서울','부산','인천','대구'])
s21

서울     1116
부산    12259
인천    65119
대구    16699
dtype: int64

In [84]:
s20 = pd.Series([628, 11075,56013,15695], index=['서울','부산','인천','대구']) 

In [68]:
s_sub = s21 - s20

In [65]:
import numpy as np
type(np.nan)

float

In [66]:
!python --version

Python 3.9.12


In [69]:
d1 = {'서울':1, '부산':2, '제주도':123123}

In [71]:
s_sub.astype(int) # nan값이 있으면 데이터 타입을 변경 할 수 없다.

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [76]:
s_sub = s21.sub(s20, fill_value=0) # NaN 인 값이 0으로 대체된 뒤에 연산이 됨.

In [77]:
s_sub.astype(int)

대구     1004
부산     1184
서울     1116
인천     9106
제주도    -628
dtype: int32

In [80]:
s21.sub(s20) # 연산만 한다.

대구     1004.0
부산     1184.0
서울        NaN
인천     9106.0
제주도       NaN
dtype: float64

In [81]:
s_sub2 = s21.sub(s20)

In [82]:
s_sub2.fillna(0)

대구     1004.0
부산     1184.0
서울        0.0
인천     9106.0
제주도       0.0
dtype: float64

In [83]:
# null이 있는지 없는지 확인가능
s_sub2.notnull() # null이면 False

대구      True
부산      True
서울     False
인천      True
제주도    False
dtype: bool

In [86]:
s21

서울     1116
부산    12259
인천    65119
대구    16699
dtype: int64

In [87]:
s20

서울      628
부산    11075
인천    56013
대구    15695
dtype: int64

In [91]:
# 증감 % 표현
rs = ((s21 - s20) / s20 * 100).round(2) # 원본데이터가 중요할 때는 round사용하면 안된다. 보기 편하기 위해 사용 한 것.
rs

서울    77.71
부산    10.69
인천    16.26
대구     6.40
dtype: float64

In [92]:
# 데이터 수정
rs['서울']

77.71

In [93]:
rs['서울'] = 0

In [95]:
rs[0] = 123
rs

서울    123.00
부산     10.69
인천     16.26
대구      6.40
dtype: float64

In [104]:
# 데이터 지우기
# del rs[0] 오류남. 접근 불가능. 인덱스 값으로만 가능
del rs['대구']
rs

부산    10.69
인천    16.26
서울    77.71
dtype: float64

In [105]:
del rs['서울']
rs

부산    10.69
인천    16.26
dtype: float64

In [106]:
rs['서울'] = 77.71
rs['대구'] = 56.40
rs

부산    10.69
인천    16.26
서울    77.71
대구    56.40
dtype: float64

In [107]:
import random

In [111]:
random.randint(0,100)

72

In [130]:
# pd.Series() 크기가 100
# 키값 100개 밸류값 100
key100 = random.sample(list(range(1000)), 100)
key80 =  random.sample(list(range(1000)), 80)
value100 = random.sample(list(range(1000)), 100)
value80 = random.sample(list(range(1000)), 80)

s100 = pd.Series(value100, index=key100)
s80 = pd.Series(value80, index=key80)

In [131]:
len(set(key80))
len(set(key100))

100

In [132]:
s_100_80_sub = s100 - s80

In [133]:
s_100_80_sub.head()

6    NaN
9    NaN
15   NaN
17   NaN
31   NaN
dtype: float64

In [134]:
for k,v in s_100_80_sub.notnull().items():
    if v:
        print(k,v)

39 True
122 True
196 True
479 True
582 True
937 True
989 True


In [137]:
s_100_80_sub[39]

44.0

In [138]:
s100[39]

350

In [139]:
s80[39]

306

In [140]:
s_100_80_sub = s100 * s80

In [385]:
data = {
'2021' : [1116, 12259, 16699, 65119],
'2020' : [628, 11075, 15695, 56013],
'2019' : [678,12700,15148,55443],
'2018' : [712, 13597, 16052, 56024],
'농지면적순위' : [4,3,2,1]
}
columns = ['농지면적순위', '2021', '2020', '2019', '2018']
index = ['서울','부산','대구','인천']
df = pd.DataFrame(data, index=index, columns=columns)
df

농지면적순위   2021   2020   2019   2018
서울       4   1116    628    678    712
부산       3  12259  11075  12700  13597
대구       2  16699  15695  15148  16052
인천       1  65119  56013  55443  56024

In [386]:
print(df.values)
print(df.index)
print(df.columns)

[[    4  1116   628   678   712]
 [    3 12259 11075 12700 13597]
 [    2 16699 15695 15148 16052]
 [    1 65119 56013 55443 56024]]
Index(['서울', '부산', '대구', '인천'], dtype='object')
Index(['농지면적순위', '2021', '2020', '2019', '2018'], dtype='object')


In [387]:
# 정보 알려줌
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 서울 to 인천
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   농지면적순위  4 non-null      int64
 1   2021    4 non-null      int64
 2   2020    4 non-null      int64
 3   2019    4 non-null      int64
 4   2018    4 non-null      int64
dtypes: int64(5)
memory usage: 192.0+ bytes


In [388]:
df.index.name = '지역'
df.columns.name = '특성'
df

특성  농지면적순위   2021   2020   2019   2018
지역                                    
서울       4   1116    628    678    712
부산       3  12259  11075  12700  13597
대구       2  16699  15695  15148  16052
인천       1  65119  56013  55443  56024

In [393]:
df["2018-2021 변화율"] = ((df['2021']-df['2018'])/df['2018']*100)
df

특성  농지면적순위   2021   2020   2019   2018  2018-2021 증가율  2018-2021 변화율
지역                                                                  
서울       4   1116    628    678    712          56.74      56.741573
부산       3  12259  11075  12700  13597          -9.84      -9.840406
대구       2  16699  15695  15148  16052           4.03       4.030650
인천       1  65119  56013  55443  56024          16.23      16.234114

In [446]:
df = df[['2018', '2019', '2020','2021','농지면적순위','2018-2021 변화율']]
df

특성   2018   2019   2020   2021  농지면적순위  2018-2021 변화율
지역                                                   
서울    712    678    628   1116       4      56.741573
부산  13597  12700  11075  12259       3      -9.840406
대구  16052  15148  15695  16699       2       4.030650
인천  56024  55443  56013  65119       1      16.234114

In [447]:
# 한 컬럼 안에서는 데이터 유형이 같아야함
df.T

지역                      서울            부산           대구            인천
특성                                                                 
2018            712.000000  13597.000000  16052.00000  56024.000000
2019            678.000000  12700.000000  15148.00000  55443.000000
2020            628.000000  11075.000000  15695.00000  56013.000000
2021           1116.000000  12259.000000  16699.00000  65119.000000
농지면적순위            4.000000      3.000000      2.00000      1.000000
2018-2021 변화율    56.741573     -9.840406      4.03065     16.234114

In [448]:
df

특성   2018   2019   2020   2021  농지면적순위  2018-2021 변화율
지역                                                   
서울    712    678    628   1116       4      56.741573
부산  13597  12700  11075  12259       3      -9.840406
대구  16052  15148  15695  16699       2       4.030650
인천  56024  55443  56013  65119       1      16.234114

In [449]:
df['2019']

지역
서울      678
부산    12700
대구    15148
인천    55443
Name: 2019, dtype: int64

In [450]:
df[['2019']]

특성   2019
지역       
서울    678
부산  12700
대구  15148
인천  55443

In [451]:
df[['2019','2021']]

특성   2019   2021
지역              
서울    678   1116
부산  12700  12259
대구  15148  16699
인천  55443  65119

In [452]:
# df['2018','2021']은 안됨. 시리즈는 1차원
df['2018']['서울']

712

In [453]:
temp = pd.Series(['a','b','c','d','e'])

In [454]:
#시리즈는 인덱스로 접근
temp[0]

'a'

In [455]:
# 데이터프레임은 밸류값으로 접근
df['2021']

지역
서울     1116
부산    12259
대구    16699
인천    65119
Name: 2021, dtype: int64

In [456]:
print(df['2021']['서울'])
print(df['2021'][0])

1116
1116


In [457]:
df

특성   2018   2019   2020   2021  농지면적순위  2018-2021 변화율
지역                                                   
서울    712    678    628   1116       4      56.741573
부산  13597  12700  11075  12259       3      -9.840406
대구  16052  15148  15695  16699       2       4.030650
인천  56024  55443  56013  65119       1      16.234114

In [458]:
df.sort_values(by='2018-2021 변화율') # 오름차순

특성   2018   2019   2020   2021  농지면적순위  2018-2021 변화율
지역                                                   
부산  13597  12700  11075  12259       3      -9.840406
대구  16052  15148  15695  16699       2       4.030650
인천  56024  55443  56013  65119       1      16.234114
서울    712    678    628   1116       4      56.741573

In [459]:
# 데이터 프레임에서 컬럼이 아닌 인덱스 바로 접근하는 방법. 여러가지가 있음.
temp_list = [1,2,3,4]
temp_list[:2]

[1, 2]

In [460]:
df[:2]

특성   2018   2019   2020   2021  농지면적순위  2018-2021 변화율
지역                                                   
서울    712    678    628   1116       4      56.741573
부산  13597  12700  11075  12259       3      -9.840406

In [461]:
# 단일 갯수가 아닌 여러개를 가지고 오려고 할때 번거로움
df[1:2]

특성   2018   2019   2020   2021  농지면적순위  2018-2021 변화율
지역                                                   
부산  13597  12700  11075  12259       3      -9.840406

In [462]:
# 인덱스를 ''로 가져오면 작성해야 할게 많음
df['서울':'부산']

특성   2018   2019   2020   2021  농지면적순위  2018-2021 변화율
지역                                                   
서울    712    678    628   1116       4      56.741573
부산  13597  12700  11075  12259       3      -9.840406

In [463]:
# loc, iloc
df.loc[['부산','대구']]

특성   2018   2019   2020   2021  농지면적순위  2018-2021 변화율
지역                                                   
부산  13597  12700  11075  12259       3      -9.840406
대구  16052  15148  15695  16699       2       4.030650

In [464]:
df

특성   2018   2019   2020   2021  농지면적순위  2018-2021 변화율
지역                                                   
서울    712    678    628   1116       4      56.741573
부산  13597  12700  11075  12259       3      -9.840406
대구  16052  15148  15695  16699       2       4.030650
인천  56024  55443  56013  65119       1      16.234114

In [465]:
df.iloc[0][0]

712.0

In [466]:
df.iloc[0][0]

712.0

In [467]:
df['2018']['서울']

712

In [468]:
df.iloc[0][0]

712.0

In [469]:
student = {
    '국어' : [80,90,70,30],
    '영어' : [90,50,100,50],
    '수학' : [70,60,50,80],
    '과학' : [50,100,70,80]
}

columns = ['국어','영어','수학','과학']
index = ['철수','영희','길동','슬기']

df = pd.DataFrame(student, index=index, columns=columns)
df


국어   영어  수학   과학
철수  80   90  70   50
영희  90   50  60  100
길동  70  100  50   70
슬기  30   50  80   80

In [470]:
df.loc['평균'] = (df.loc['철수'] + df.loc['영희'] + df.loc['길동']+ df.loc['슬기']) / 4
df

국어     영어    수학     과학
철수  80.0   90.0  70.0   50.0
영희  90.0   50.0  60.0  100.0
길동  70.0  100.0  50.0   70.0
슬기  30.0   50.0  80.0   80.0
평균  67.5   72.5  65.0   75.0

In [471]:
df['평균'] = (df['국어'] + df['영어'] + df['수학']+ df['과학']) / 4
df

국어     영어    수학     과학    평균
철수  80.0   90.0  70.0   50.0  72.5
영희  90.0   50.0  60.0  100.0  75.0
길동  70.0  100.0  50.0   70.0  72.5
슬기  30.0   50.0  80.0   80.0  60.0
평균  67.5   72.5  65.0   75.0  70.0