In [ ]:
#NumPy 꼭 알아야하는 파키지. 매우 중요!!!!
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
#0으로 초기화 배열 why?
arr = np.zeros((3,3)) 
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 빈 값으로 만들어진 배열 -> 쓰레기 값이 들어가있다.
arr = np.empty((4,3))
print(arr)

[[2.88445168e-316 6.91065864e-310 6.91063181e-310]
 [6.91065864e-310 6.91063181e-310 6.91065864e-310]
 [6.91063181e-310 6.91065864e-310 6.91063181e-310]
 [6.91065864e-310 6.91063181e-310 6.91065864e-310]]


In [ ]:
# 1로 초기화된 배열
arr = np.ones((3,3))
print(arr)  
# 수 뒤에 .은 why? 실수형을 기본으로 하기때문에 type이 다 같아서 속도가 빨라짐

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# NumPy 배열의 생성
arr = np.arange(10)     # 정수형 배열
print(arr)              #몇 차원 배열인지 ->  [가 2개 : 2차원

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# ndarray 배열의 모양, 차수, 데이터 타입 확인

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 배열의 모양을 확인, 습관적으로 확인부터 하자.
arr.shape

(2, 3)

In [ ]:
# 배열의 단순 차원만 확인
arr.ndim

2

In [ ]:
# 배열의 data type
arr.dtype

dtype('int64')

In [ ]:
# 데이터 타입 변경
arr_float = arr.astype(np.float64)
arr_float.dtype

dtype('float64')

In [ ]:
arr_str = np.array(['1','2','3'])
arr_str.dtype   #유니코드

dtype('<U1')

In [ ]:
arr_int = arr_str.astype(np.int64)
arr_int.dtype

dtype('int64')

In [ ]:
#NumPy 배열(ndarray)의 연산

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [ ]:
np.add(arr1, arr2)

array([[ 6,  8],
       [10, 12]])

In [ ]:
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [ ]:
np.multiply(arr1, arr2)

array([[ 5, 12],
       [21, 32]])

In [ ]:
# ndarray 배열 슬라이싱 하기

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr.ndim

2

In [ ]:
arr_1 = arr[:2,1:3]   #  :2 = 처음~ 2 전까지=  0, 1 -> 행
print(arr_1)          # 1:3 = 2 ~ 3 전까지 = 1, 2 -> 열

[[2 3]
 [5 6]]


In [ ]:
arr[0,2]      #배열의 크기를 모를때 0자리에 -1을 주면 맨 끝 데이터를 줌 

3

In [ ]:
arr[[0,1,2],[2,0,1]]

array([3, 4, 8])

In [ ]:
idx = arr > 3
print(idx)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
print(arr[idx])     #idx를 arr의 매개변수로
                    #조건에 맞는 것이 별도의 배열이 되어서 출력

[4 5 6 7 8 9]


In [ ]:
# .csv 파일 불러오기

redwine = np.loadtxt(fname='winequality-red.csv',delimiter=';',skiprows=1) 
#구별자로 ';'사용됐다 / 첫번째 자리는 무시하겠다

print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [ ]:
# 합계

print(redwine.sum())    # 전체 데이터의 합 

152084.78194


In [ ]:
# 평균

print(redwine.mean())

7.926036165311652


In [ ]:
# 축(axis) 가로=0번축, 세로=1번축
print(redwine.sum(axis=0))   # why? 12개 컬럼

[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]


In [ ]:
print(redwine.sum(axis=1))

[ 74.5438  123.0548   99.699   ... 100.48174 105.21547  92.49249]


In [ ]:
print(redwine.mean(axis=0))

[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [ ]:
redwine[:,0].mean()    # 전부:첫번째 컬럼(열0번).첫번째 컬럼의 평균

8.31963727329581

In [ ]:
redwine.max(axis=0)    #칼럼 별 최댓값 가장 센 알코올:14.9, 가장 좋은 와인:8

array([ 15.9    ,   1.58   ,   1.     ,  15.5    ,   0.611  ,  72.     ,
       289.     ,   1.00369,   4.01   ,   2.     ,  14.9    ,   8.     ])

In [ ]:
redwine.min(axis=0)

array([4.6    , 0.12   , 0.     , 0.9    , 0.012  , 1.     , 6.     ,
       0.99007, 2.74   , 0.33   , 8.4    , 3.     ])

슬라이싱. 축의 개념 너무나도 중요!!!